#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

const INPUT_DIR = path.resolve("levels");
const OUTPUT_FILE = path.resolve("src/levels/generated/packed-levels.ts");

const CELL_TO_CODE = {
  "#": 0,
  " ": 1,
  ".": 2,
  "$": 3,
  "@": 4,
  "+": 5,
  "*": 6,
};

const CODE_TO_CELL = ["#", " ", ".", "$", "@", "+", "*"];

class BitWriter {
  constructor() {
    this.bytes = [];
    this.current = 0;
    this.bitCount = 0;
  }

  write(value, bits) {
    for (let bitIndex = bits - 1; bitIndex >= 0; bitIndex -= 1) {
      const bit = (value >> bitIndex) & 1;
      this.current = (this.current << 1) | bit;
      this.bitCount += 1;

      if (this.bitCount === 8) {
        this.bytes.push(this.current);
        this.current = 0;
        this.bitCount = 0;
      }
    }
  }

  toUint8Array() {
    if (this.bitCount > 0) {
      this.current <<= 8 - this.bitCount;
      this.bytes.push(this.current);
      this.current = 0;
      this.bitCount = 0;
    }
    return Uint8Array.from(this.bytes);
  }
}

function inferTierFromName(fileName) {
  const lowerName = fileName.toLowerCase();
  if (lowerName.includes("hard")) {
    return "hard";
  }
  if (lowerName.includes("medium")) {
    return "medium";
  }
  return "unfiltered";
}

function parseLevelBlocks(rawText, fileName) {
  const levels = [];
  const lines = rawText.replace(/\r/g, "").split("\n");
  let currentRows = [];

  const pushCurrent = () => {
    if (currentRows.length === 0) {
      return;
    }

    levels.push([...currentRows]);
    currentRows = [];
  };

  for (const line of lines) {
    if (line.startsWith(";")) {
      pushCurrent();
      continue;
    }

    if (line.trim().length === 0) {
      continue;
    }

    currentRows.push(line);
  }

  pushCurrent();

  if (levels.length === 0) {
    throw new Error(`No levels parsed from ${fileName}`);
  }

  return levels;
}

function encodeLevels(levelRows, fileName) {
  const writer = new BitWriter();

  if (levelRows.length > 65535) {
    throw new Error(`Too many levels in ${fileName}: ${levelRows.length}`);
  }

  writer.write(levelRows.length, 16);

  for (const rows of levelRows) {
    const height = rows.length;
    const width = Math.max(...rows.map((row) => row.length));

    if (height <= 0 || height > 31 || width <= 0 || width > 31) {
      throw new Error(
        `Unsupported size in ${fileName}: ${width}x${height} (max 31x31)`
      );
    }

    writer.write(width, 5);
    writer.write(height, 5);

    for (let y = 0; y < height; y += 1) {
      const row = rows[y] ?? "";
      for (let x = 0; x < width; x += 1) {
        const cell = row[x] ?? " ";
        const code = CELL_TO_CODE[cell];

        if (code === undefined) {
          throw new Error(
            `Unsupported cell '${cell}' in ${fileName} at (${x}, ${y})`
          );
        }

        writer.write(code, 3);
      }
    }
  }

  const bytes = writer.toUint8Array();
  return Buffer.from(bytes).toString("base64");
}

function buildPackedFile() {
  const fileNames = fs
    .readdirSync(INPUT_DIR)
    .filter((fileName) => fileName.endsWith(".txt"))
    .sort();

  if (fileNames.length === 0) {
    throw new Error(`No .txt files found in ${INPUT_DIR}`);
  }

  const packedEntries = [];

  for (const fileName of fileNames) {
    const sourcePath = path.join(INPUT_DIR, fileName);
    const rawText = fs.readFileSync(sourcePath, "utf8");
    const levels = parseLevelBlocks(rawText, fileName);
    const encoded = encodeLevels(levels, fileName);

    packedEntries.push({
      name: fileName,
      tier: inferTierFromName(fileName),
      levelCount: levels.length,
      data: encoded,
    });
  }

  const totalLevels = packedEntries.reduce((sum, entry) => sum + entry.levelCount, 0);

  const header = `/* Auto-generated by scripts/pack-boxoban.mjs */\n` +
    `/* Source symbols: ${CODE_TO_CELL.join(" ")} */\n\n` +
    `export type PackedLevelTier = "unfiltered" | "medium" | "hard";\n\n` +
    `export type PackedLevelFile = {\n` +
    `  name: string;\n` +
    `  tier: PackedLevelTier;\n` +
    `  levelCount: number;\n` +
    `  data: string;\n` +
    `};\n\n`;

  const body =
    `export const packedLevelFiles: PackedLevelFile[] = ${JSON.stringify(
      packedEntries,
      null,
      2
    )} as const;\n\n` +
    `export const packedLevelCount = ${totalLevels};\n`;

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, `${header}${body}`, "utf8");

  const rawBytes = packedEntries.reduce(
    (sum, entry) => sum + Buffer.from(entry.data, "base64").length,
    0
  );

  console.log(`Packed ${packedEntries.length} files (${totalLevels} levels).`);
  console.log(`Raw packed bytes: ${rawBytes}`);
  console.log(`Wrote: ${OUTPUT_FILE}`);
}

buildPackedFile();
